#!/usr/bin/env node
/**
 * Regenerate packages/server/src/publish/libs.generated.ts from the pinned
 * in-worker compiler's own lib files.
 *
 * The publish pipeline runs the TypeScript compiler inside the Worker, and a
 * compiler with no lib files knows no Promise and no Response. The lib chain
 * cannot be read from disk in a Worker, so it is embedded as a generated
 * module: the transitive `/// <reference lib="..." />` closure of the two
 * roots the publish compile declares. A unit test pins the generated content
 * to node_modules, so an upgrade of the alias dependency fails loudly until
 * this script is re-run.
 *
 * Run from the repository root:  node scripts/generate-tslibs.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";

const require = createRequire(new URL("../packages/server/package.json", import.meta.url));
const libDir = join(dirname(require.resolve("in-worker-typescript/package.json")), "lib");

export const ROOT_LIBS = ["lib.es2023.d.ts", "lib.webworker.d.ts"];

const REFERENCE = /\/\/\/\s*<reference\s+lib="([^"]+)"\s*\/>/g;

export const closure = () => {
  const files = new Map();
  const queue = [...ROOT_LIBS];
  while (queue.length > 0) {
    const name = queue.shift();
    if (files.has(name)) {
      continue;
    }
    const content = readFileSync(join(libDir, name), "utf8");
    files.set(name, content);
    for (const match of content.matchAll(REFERENCE)) {
      queue.push(`lib.${match[1]}.d.ts`);
    }
  }
  return new Map([...files.entries()].sort(([a], [b]) => a.localeCompare(b)));
};

const main = () => {
  const files = closure();
  const version = JSON.parse(readFileSync(join(libDir, "..", "package.json"), "utf8")).version;
  const entries = [...files.entries()]
    .map(([name, content]) => `  ${JSON.stringify(name)}: ${JSON.stringify(content)},`)
    .join("\n");
  const generated =
    `// Generated by scripts/generate-tslibs.mjs from typescript@${version} (the\n` +
    "// in-worker-typescript alias). Do not edit; re-run the script instead.\n" +
    "// A unit test pins this to node_modules so the two cannot drift apart.\n" +
    `export const LIB_VERSION = ${JSON.stringify(version)};\n` +
    "export const LIB_FILES: Readonly<Record<string, string>> = {\n" +
    `${entries}\n` +
    "};\n";
  const target = new URL("../packages/server/src/publish/libs.generated.ts", import.meta.url);
  writeFileSync(target, generated);
  console.error(`wrote ${files.size} lib files (${generated.length} bytes) to ${target.pathname}`);
};

if (process.argv[1] === new URL(import.meta.url).pathname) {
  main();
}
